#!/usr/bin/python

#if __name__ == '__main__' and __package__ is None:
#    from os import sys, path
#    sys.path.append(path.dirname(path.dirname(path.abspath(__file__))))

import sys, os

my_path = '/srv/www/JurDev/eStation2'
#abspath = os.path.dirname()
#sys.path.append(abspath)
os.chdir(my_path)

if my_path not in sys.path:
    sys.path.append(my_path)

import web
import locals

import database.querydb as querydb

#sys.path.remove('/srv/www/MarcoDev/eStation2')
#sys.path.remove('/srv/www/JurDev/eStation2')


WEBPY_COOKIE_NAME = "webpy_session_id"

urls = (
    "/ingestion", "Ingestion",
    "/dataacquisition", "DataAcquisition",
    "/pa(.*)", "ProductAcquisition",
    "/template", "TemplatePage",
    #"/(.+)/(.+)", "EsApp",
    #"/(.+)/", "EsApp",
    "/", "EsApp")

app = web.application(urls, globals(), autoreload=True)
application = app.wsgifunc()
#session = web.session.Session(app, web.session.DiskStore('../logs/mstmp/webpySessions'))


class EsApp:
    def __init__(self):
        self.lang = "en"

    def GET(self):
        #return web.ctx
        render = web.template.render(my_path+'/apps/gui/esapp')
        return render.index()
        #getparam = web.input(lang=self.lang)
        #return render.index(getparam.lang)


class Ingestion:
    def __init__(self):
        self.lang = "en"

    def GET(self):
        #return web.ctx
        ingestion = querydb.get_ingestions(echo=False)
        return ingestion


class DataAcquisition:
    def __init__(self):
        self.lang = "en"

    def GET(self):

        datacq = querydb.get_dataacquisitions(echo=False)
        return datacq


class ProductAcquisition:
    def __init__(self):
        self.lang = "en"

    def GET(self, params):
        #return web.ctx
        #if not activated:
        #    activated = True
        getparams = web.input()
        #return getparams.activated
        products = querydb.get_products(echo=False, activated=getparams.activated)
        return products


class TemplatePage:
    def __init__(self):
        self.render = web.template.render(my_path+'/templates/')

    def GET(self):
        getInput=web.input(name="World")
        return self.render.mytemplate("mytitle", getInput.name)

if __name__ == "__main__":
    app.run()